spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timebank
    username: timebank
    password: timebank
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

logging.level:
  kookmin.software.capstone2023.timebank.infrastructure.client.kakao.KakaoRestClient: DEBUG

auth:
  access-token:
    secret-key: 12345678901234567890123456789012