name: Lint
on:
  pull_request:
    branches:
      - main

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/timebank

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          android: false
          fail_on_error: true
          level: warning
