name: timebank - 02 - CI CD

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2

      - name: Change Dir and Docker compose 
        run: |
          cd /home/dkadmin/actions-runner/_work/timebank-2023-02/timebank-2023-02/backend/timebank                                                                                              
          docker compose -f docker-compose.yml up -d --build
